version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fastapi_project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./script_Database.sql:/docker-entrypoint-initdb.d/script_Database.sql

  fastapi:
    image: joanlebaptiste/fastapi_agregation_joanlebaptiste:latest
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    environment:
      ENVIRONMENT: docker
      DATABASE_URL_DOCKER: mysql+mysqlconnector://user:password@db:3306/fastapi_project
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  mysql_data:
