name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build: # BUILD AND PUSH TO DOCKER HUB (joanlebaptiste), using GitHub secrets to login
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt 

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          docker build -t $DOCKER_USERNAME/fast_api_agregation_joanlebaptiste:latest .

      - name: Push Docker image to Docker Hub
        # if: success()  # si test validé on peut push, pas encore implémenté
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          docker push $DOCKER_USERNAME/fast_api_agregation_joanlebaptiste:latest
